### ISSUE TITLE
Setting bot username

### ISSUE THREAD

**Issue by tommywalkie** [museun/twitchchat#115]
Managed to run the simple bot example on the README just fine with anonymous login and with TLS, it doesn't respond to messages but I suppose this is an expected behaviour with anonymous users. 

Then, I tried making it work with an actual token, I figured that the `TWITCH_PASS` env variable is expecting a token with `oauth:` prefix I have to get from [twitchapps.com/tmi/](https://twitchapps.com/tmi/) and then I could connect the bot and make it respond to `!hello`.

But whatever value I put in `TWITCH_NICK` or in app name field on Twitch Developers Console, it is always replying as my actual Twitch username.
Is this a bug with `TWITCH_NICK` or did I miss something ?

**Comment by tommywalkie** [comment]
**EDIT** : 
Turns out it always use the username of the one user who logged via OAuth. ([reference](https://discuss.dev.twitch.tv/t/twitch-chat-bot-name/22039))
> The bot will always use the username associated with the OAuth token. If you want to change the name you either need to log in to the bot account on Twitch and change their username, or create a new account with the name you want and get a new OAuth token with that user.

So, what's the purpose of `TWITCH_NICK` ?

**Comment by museun** [comment]
IIRC, that nickname has to be provided and must match the associated OAuth nickname.

Part of the irc 'registration' is sending the PASS and NICK commands. But Twitch doesn't really document this, so I'm just doing what the protocol dictates. Ideally, the documentation should explain this.

Perhaps the NICK command isn't required, I've never tried without it.

**Comment by museun** [comment]
I just tested it. The `NICK` command is required. Since I'm not willing to write an OAuth v2/OIDC client and I've yet to find one that doesn't bring in 300 deps, I'll continue to require the user to provide their associated nickname with their OAuth token. An alternative would be that we could just generate a random name (`twitchchat_{left}_{right}`) and just get the real nickname from the Server's reply. 

In summary: Twitch uses a modified IRC server for its chat. This server requires you to send the `PASS` command with your OAuth token and then a `NICK` command with a nickname to connect.  If one was to provide the anonymous login (`justinfan1234`) just for the name and a real OAuth, Twitch will still treat it as an anonymous connection (read-only, no advanced capabilities). Any name that isn't `justinfan1234` would work. To be a 'good' player, I could generate a name that shouldn't be confused with a real user. Twitch doesn't seem to compare the name to the OAuth token (for likely good security reasons -- don't leak names associated with a token). But, like most Twitch chat stuff, this isn't documented and just a guess. 

The correct thing to do is to have the user provide the paired name. But its not required..

**Comment by tommywalkie** [comment]
@museun Thanks for the very informative response ! These test results explain a lot, wish Twitch could have have explained it better. Nice work on `twitchchat` by the way, this crate is the only working Rust based Twitch IRC related project I've found.

**Comment by museun** [comment]
Closing this. I think the current behavior is the most correct/acceptable.
